# Generated by Django 5.2.5 on 2025-08-12 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('properties', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('properties', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='Explorer.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='Explorer.node')),
            ],
        ),
    ]
